apiVersion: v1
kind: PersistentVolume
metadata:
  name: e2e-testing-manager-postgres-pv
  labels:
    type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/e2e-testing-manager-postgres"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e2e-testing-manager-postgres-pvc
  namespace: test-e2e
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
