apiVersion: v1
kind: Service
metadata:
  name: e2e-testing-manager-postgres
  namespace: test-e2e
spec:
  selector:
    app: e2e-testing-manager-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
