name: E2E Test Manager API - Continuous Integration

on:
  push:
    branches: [ "develop", "hotfix/*" ]
  pull_request:
    branches: [ "develop", "hotfix/*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn test